#!/bin/bash

[ $# == 0 ] && echo common or unique ?

exec 1>> $HOME/.local/log/borg 2>&1

if [[ "$@" == *"common"* ]]
then
    echo ==[Starting common]==

    borg create \
        --show-rc \
        --progress \
        --compression auto,zstd,22 \
        /data/backup::'common-{now}'  \
        $HOME/doc \
        $HOME/pic \
        $HOME/project \
        $HOME/tmp \
        $HOME/vid \
        $HOME/ucll \
        $HOME/music \
        $HOME/.android \
        $HOME/.config \
        $HOME/.local/bin \
        $HOME/.local/bookmarks \
        $HOME/.local/calendars \
        $HOME/.local/history \
        $HOME/.local/people \
        $HOME/.local/repo \
        $HOME/.local/share \
        $HOME/.local/templates \
        $HOME/.local/unison/*.prf \
        $HOME/.ssh \
        $HOME/.zprofile \
        $HOME/.zshenv \
        $HOME/.zshrc

    common_create_exit="Common create exit: $?"

    borg prune                          \
        --prefix 'common-'          \
        --show-rc                       \
        --keep-daily    7               \
        --keep-weekly   4               \
        --keep-monthly  6               \
        /data/backup

    common_prune_exit="Common prune exit: $?"

fi

if [[ "$@" == *"unique"* ]]
then
    echo ==[Starting unique]==

    borg create \
        --show-rc \
        --progress \
        --compression auto,zstd,22 \
        /data/backup::'{hostname}-{now}' \
        $HOME/.local/log \
        $HOME/.local/unison \
        $HOME/.local/unique

    unique_create_exit="Unique create exit: $?"

    borg prune \
        --prefix '{hostname}-'          \
        --show-rc                       \
        --keep-daily    7               \
        --keep-weekly   4               \
        --keep-monthly  6               \
        /data/backup

    unique_prune_exit="Unique prune exit: $?"

fi

trash-empty -f

echo -e "$common_create_exit\n$common_prune_exit\n$unique_create_exit\n$unique_prune_exit" >> $HOME/.local/log/masterlog
