#!/bin/bash

# grep '^EU' ~/doc/countrycodes.txt | cut -d' ' -f 2 | xargs | tr ' ' '|'
europe="AL|AD|AZ|AT|AM|BE|BA|BG|BY|HR|CY|CZ|DK|EE|FO|FI|AX|FR|GE|DE|GI|GR|VA|HU|IS|IE|IT|KZ|LV|LI|LT|LU|MT|MC|MD|ME|NL|NO|PL|PT|RO|RU|SM|RS|SK|SI|ES|SJ|SE|CH|TR|UA|MK|GB|GG|JE|IM"
apiurl="https://api.invidious.io/instances.json"
jqcmd='.[] | .[1] | select( .region != null and (.region | test("'$europe'")) and .type == "https") | .uri'

mkdir -p ~/.cache/best-instances

curl -s $apiurl \
    | jq "$jqcmd" \
    | tr -d '"' \
    | tee ~/.cache/best-instances/invidious.txt
