#!/bin/bash

source ~/.cache/wal/colors.sh
killall dunst >/dev/null 2>&1
printf "$(cat ~/.config/dunst.conf)\nbackground = \"$color0\"\nforeground = \"$color1\"" \
    | dunst -config - \
    >> ~/.local/log/dunst 2>&1
