#!/bin/bash

exec 2>/dev/null
TERMINAL_OPTIONS=${TERMINAL_OPTIONS:- -t floater}
MENUCMD=${MENUCMD:-fzf}

$TERMINAL $TERMINAL_OPTIONS -e $SHELL --interactive -c "$MENUCMD < /proc/$$/fd/0 > /proc/$$/fd/1"

# TODO
# i3-msg -t get_workspaces | jq '.[] | select(.focused).rect | .width*0.90, .height*0.5, .x+.width*0.05, .y+.height*0.25' | xargs | read w h x y
# xdotool search --name floater windowmove $x $y windowsize $w $h
