#!/usr/bin/env bash

shopt -s nullglob globstar

user=0
if [[ $1 == "username" ]]; then
	user=1
	shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

opts=" --history=$HOME/.local/history/fzf/pass --query='$(tail -1 $HOME/.local/history/fzf/pass)'"
username=$(printf '%s\n' "${password_files[@]}" | FZF_OPTIONS="$opts" dmenu "$@")

[[ -n $username ]] || exit

if [[ $user -eq 0 ]]; then
	pass show -c "$username"
else
	pass show "$username" | tail -1 | xclip -rmlastnl -selection clipboard
fi
