#!/bin/bash

WALDIR="$HOME/.cache/wal"

[[ $1 == -R ]] \
    && wal -R

[[ $1 == -I ]] && {
    wal --iterative -i ~/pic/hyperborea
    convert $(cat $WALDIR/wal) -bordercolor transparent -border 20%x20% $WALDIR/generated-wal1.png
}

source $WALDIR/colors.sh
bgs -R -C $color0 $WALDIR/generated-wal1.png
pywal-zathura-colors > $WALDIR/colors-zathura
setsid colored-dunst &

# if [[ $1 = -p ]]
# then
#     theme=$(wal --theme \
#         | sed '/Dark Themes/,/Light Themes/ s/ - /dark:/;
#             /Light Themes/,/Extra/ s/ - /light:/' \
#         | head -n-4 \
#         | grep -Pv ':$' \
#         | cat - <(printf "random_dark\nrandom_light\n") \
#         | fzf \
#         | sed 's/dark://'
#     )
# elif [[ $1 = -l ]]
# then
#     theme=random_light
# else
#     theme=random_dark
# fi

# [ -z $theme ] && exit

# if grep -Pq '^light:' <<< $theme
# then
#     theme=$(sed 's/light://' <<< $theme)
#     wal -l --theme $theme
# else
#     wal --theme $theme
# fi

# sed "s/green/$color0/ ; s/black/$color1/" ~/.config/wal/wallpaper-template.svg \
#  | convert - ~/.cache/wal/generated-wal1.png
