#!/bin/bash

# [[ "$1" == "create" ]] && {
#     tmux new-session -s repl-session -n repl
#     exit
# }

while IFS= read -r line
do
    echo "$line"
    tmux send-keys -l -t repl "$line"
    tmux send-keys -t repl Enter
done
