#!/bin/bash

youtube-dl --download-archive archive.txt \
	--write-description \
    --write-thumbnail \
    --add-metadata \
    --xattrs \
	--ignore-errors \
	-o '%(upload_date)s-%(title)s-%(id)s.%(ext)s' \
	"$1"
